import type { NextPage } from "next";
import Head from "next/head";
import Blogs from "../components/Blogs";
import Map from "../components/Map";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="fullflex">
        <div className="container">
          <h1 className="text-6xl text-center">Intertots Trillingual School</h1>
        </div>
      </main>

      <Map />
      <Blogs />
    </>
  );
};

export default Home;
